### ISSUE TITLE
could not find load file: /usr/lib/llvm-3.5/share/llvm/cmake/LLVMExports.cmake on raspbian

### ISSUE THREAD

**Issue by ThomasRuby** [abenkhadra/llvm-pass-tutorial#1]
Hi,
I'm running LLVM on my raspbian. The last llvm version on official repo is 3.5 and this is why I have this error:

```
CMake Error at /usr/share/llvm-3.5/cmake/LLVMConfig.cmake:50 (include):
  include could not find load file:

    /usr/lib/llvm-3.5/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)

CMake Error at /usr/share/llvm-3.5/cmake/LLVMConfig.cmake:53 (include):
  include could not find load file:

    /usr/lib/llvm-3.5/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)
```

Seems that it's searching in the wrong directory : `/usr/lib/llvm-3.5` instead of `/usr/share/llvm-3.5` 
… 

By the way, I don't care ^^'

I just wanted to link the **skeleton-pass** to my compiled llvm (4.0) by using your cmake command:
`LLVM_DIR="/home/pi/LLVM/llvm_build/lib/cmake/llvm" cmake ..`
But it states the same error… as if cmake does not want to consider `$LLVM_DIR` global variable here.

```
-- Found LLVM 3.5.0
-- Using LLVMConfig.cmake in: /usr/share/llvm-3.5/cmake
```

It's better to use **-DLLVM_DIR** option to cmake.

Remarque: my "cmakes" directory is not in `$LLVM_BUILD/share/llvm/cmake` 
Maybe they moved it?

**Comment by abenkhadra** [comment]
I originally created this tutorial because I had a similar issue with Ubuntu 16.04 where the default llvm package is broken. I'm not sure about your specific case since you are using an older llvm version. However,  you might find the following commands useful  after replacing `${LLVM_HOME}` with your specific folder. 

```cmake
set(LLVM_DIR ${LLVM_HOME}/share/llvm/cmake)
find_package(LLVM REQUIRED CONFIG)
add_definitions(${LLVM_DEFINITIONS})
include_directories(${LLVM_INCLUDE_DIRS})
link_directories(${LLVM_LIBRARY_DIRS})
```

Hope this helps
